apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - image: harbor.apps.estreetz.com/uniwork/test-reactjs:latest
        name: nginx-sample-fleet
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 150m
            memory: 100Mi
      imagePullSecrets:
      - name: harbor
